### ISSUE TITLE
About displacement boundary conditions

### ISSUE THREAD

**Issue by bibiooi** [JinshuaiBai/LSWR_loss_function_PINN#1]
Hello,professor,your paper inspired me a lot,but,I have a question don't understand,why the displacement boundary condition has been naturally satisfied,I can't find the answer in the code. I will appreciate it if you solve my confusion.

**Comment by JinshuaiBai** [comment]
For example, if you want to impose the boundary condition u(x=a)=0. You can do the following modifications:  
1. Build up your feedforward neural network (FNN) that maps x to u'. We denote this network mapping function as F(x)=u'.  
2. Let the network mapping function time (x-a) as the final output. Therefore, the overall formula will be u=(x-a)u'=(x-a)F(x).  

By doing so, as you can see, the final formula can ensure that u=0 when x=a. Moreover, for x≠0, u can be any real value.  
Hope this can answer your question.

**Comment by bibiooi** [comment]
Thank you for your answer!!

**Comment by bibiooi** [comment]
> 例如，如果要施加边界条件 u（x=a）=0。您可以进行以下修改：
> 
> 1. 建立将 x 映射到您的前馈神经网络 （FNN）。我们将此网络映射函数表示为 F（x）=u'。
> 2. 让网络映射函数时间 （x-a） 作为最终输出。因此，总体公式将为 u=（x-a）u'=（x-a）F（x）。
> 
> 通过这样做，正如你所看到的，最终公式可以确保当 x=a 时 u=0。此外，对于 x≠0，您可以是任何实际值。希望这能回答你的问题。

Dear professor,I'm sorry to bother you again,through your way,I try to change the boundary conditions : u=0,v=0(x=0),I write the formula as u = x(u'),v = x(v'),unfortunately,I can't get the right result.Can you tell me if this formula is correct?

**Comment by JinshuaiBai** [comment]
> > 例如，如果要施加边界条件 u（x=a）=0。您可以进行以下修改：
> > 
> > 1. 建立将 x 映射到您的前馈神经网络 （FNN）。我们将此网络映射函数表示为 F（x）=u'。
> > 2. 让网络映射函数时间 （x-a） 作为最终输出。因此，总体公式将为 u=（x-a）u'=（x-a）F（x）。
> > 
> > 通过这样做，正如你所看到的，最终公式可以确保当 x=a 时 u=0。此外，对于 x≠0，您可以是任何实际值。希望这能回答你的问题。
> 
> Dear professor,I'm sorry to bother you again,through your way,I try to change the boundary conditions : u=0,v=0(x=0),I write the formula as u = x(u'),v = x(v'),unfortunately,I can't get the right result.Can you tell me if this formula is correct?

If you want to implement u(x=0)=0 and v(x=0)=0, your formula is correct.
You may check the code in "PINN.py", "Dif_op_x.py" and "Dif_op_y.py".
Note that in "Dif_op_x" and "Dif_op_y", you also need to write down your formula so that the gradients with respect to x and y coordinates are correct.
