### ISSUE TITLE
Code for 3D cube geometry

### ISSUE THREAD

**Issue by ruchitkini** [JinshuaiBai/LSWR_loss_function_PINN#4]
Hello @JinshuaiBai ,

I was wondering if you could share the code for the 3D cube geometry that you have trained. I am facing some issues in the training. Even though I get low losses, I don't see my solution converging. 

Thanks

**Comment by JinshuaiBai** [comment]
Sorry for this late response, I can send you the code by email. Could you please send me an email so that I can have your email address?

**Comment by Ddkowner** [comment]
> Sorry for this late response, I can send you the code by email. Could you please send me an email so that I can have your email address?

Hi Dr. Bai
I have been working hard to learn elasticity recently in an attempt to understand formulas. But deriving these formulas into three dimensions is still too difficult for me. Please also send me the code for learning. My email address is: wertmnbvkf@gmail.com. Thanks a lot!

**Comment by JinshuaiBai** [comment]
> [Ddkowner](/Ddkowner)

The code has been sent to your email address.

**Comment by ruchitkini** [comment]
> Sorry for this late response, I can send you the code by email. Could you please send me an email so that I can have your email address?

you can send the code to ruchitkini@gmail.com.
Thankyou.

**Comment by JinshuaiBai** [comment]
> > Sorry for this late response, I can send you the code by email. Could you please send me an email so that I can have your email address?
> 
> you can send the code to [ruchitkini@gmail.com](mailto:ruchitkini@gmail.com). Thankyou.

The code has been sent to your email address.
Please check.

**Comment by jackliuzefeng** [comment]
I also want the 3D code, could you please send me a copy? Thank you very much, here is myt email address 375143041@qq.com
